################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
DSPLib_1_30_00_02/source/transform/msp_cmplx_bitrev_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_bitrev_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_bitrev_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_bitrev_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_auto_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_auto_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_fixed_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_fixed_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_fft_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_auto_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_auto_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_fixed_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_fixed_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_cmplx_ifft_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_fft_auto_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_fft_auto_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_fft_fixed_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_fft_fixed_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_fft_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_fft_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_ifft_auto_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_ifft_auto_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_ifft_fixed_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_ifft_fixed_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_ifft_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_ifft_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_split_iq31.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_split_iq31.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_split_q15.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_split_q15.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"

DSPLib_1_30_00_02/source/transform/msp_transform_tables.obj: C:/ti/msp/DSPLib_1_30_00_02/source/transform/msp_transform_tables.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'MSP430 Compiler: "$<"'
	"C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/bin/cl430" -vmspx --data_model=restricted -O3 --opt_for_speed=5 --use_hw_mpy=F5 --include_path="C:/ti/ccs2100/ccs/ccs_base/msp430/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/driverlib/MSP430FR5xx_6xx" --include_path="C:/ti/ccs2100/ccs/tools/compiler/ti-cgt-msp430_21.6.2.LTS/include" --include_path="C:/Users/Oguzm/OneDrive - ozyegin.edu.tr/Desktop/Github_Projects/TrentoProjects/Model_Phase/inc" --include_path="C:/ti/msp/DSPLib_1_30_00_02/include" --advice:power="none" --advice:hw_config=all --define=__MSP430FR5994__ --define=_MPU_ENABLE --define=DEPRECATED -g --printf_support=full --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --preproc_with_compile --preproc_dependency="DSPLib_1_30_00_02/source/transform/$(basename $(<F)).d_raw" --obj_directory="DSPLib_1_30_00_02/source/transform" $(GEN_OPTS__FLAG) "$<"


